hibernate:
  dialect: org.hibernate.dialect.H2Dialect
  hbm2ddl:
    auto: false
  show_sql: true

init-db: true
init-scripts:
  - schema.sql
  - data.sql

spring:
  datasource:
    driver-class-name: org.h2.Driver
    platform: h2
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: false
      format-sql: true
    show-sql: true
  profiles: dev

---

hibernate:
  dialect: org.hibernate.dialect.H2Dialect
  hbm2ddl:
    auto: false
  show_sql: true

init-db: true
init-scripts:
  - schema.sql
  - data.sql

spring:
  datasource:
    driver-class-name: org.h2.Driver
    platform: h2
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: false
      format-sql: true
    show-sql: true
  profiles: test

---

hibernate:
  dialect: org.hibernate.dialect.H2Dialect
  hbm2ddl:
    auto: false
  show_sql: true

init-db: true
init-scripts:
  - schema.sql
  - data.sql

spring:
  datasource:
    driver-class-name: org.h2.Driver
    platform: h2
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: false
      format-sql: true
    show-sql: true
  profiles: pro
